#pragma once

enum RequestId : uint8_t {
	LOGIN_REQUEST,
	SIGNUP_REQUEST,
	LOGOUT_REQUEST,
	GET_ROOMS_REQUEST,
	GET_PLAYERS_IN_ROOM_REQUEST,
	GET_HIGHSCORES_REQUEST,
	JOIN_ROOM_REQUEST,
	CREATE_ROOM_REQUEST
} typedef RequestId;